all:
	g++ -g -w -std=c++14 asfercloudmoveclient.cpp -lprotobuf -o asfercloudmoveclient
	g++ -g -w -std=c++14 asfercloudmoveserver.cpp -lprotobuf -o asfercloudmoveserver
clean:
	rm asfercloudmoveclient asfercloudmoveserver

