all:
	g++ -g -w -std=c++14 asfercloudmoveclient.cpp -o asfercloudmoveclient -lprotobuf -lpthread
	g++ -g -w -std=c++14 asfercloudmoveserver.cpp -o asfercloudmoveserver -lprotobuf -lpthread
clean:
	rm asfercloudmoveclient asfercloudmoveserver

