// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: currency.proto

#ifndef PROTOBUF_currency_2eproto__INCLUDED
#define PROTOBUF_currency_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace currency {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_currency_2eproto();
void protobuf_AssignDesc_currency_2eproto();
void protobuf_ShutdownFile_currency_2eproto();

class Currency;

// ===================================================================

class Currency : public ::google::protobuf::Message {
 public:
  Currency();
  virtual ~Currency();

  Currency(const Currency& from);

  inline Currency& operator=(const Currency& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Currency& default_instance();

  void Swap(Currency* other);

  // implements Message ----------------------------------------------

  Currency* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Currency& from);
  void MergeFrom(const Currency& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string uuid_and_denom = 2;
  inline bool has_uuid_and_denom() const;
  inline void clear_uuid_and_denom();
  static const int kUuidAndDenomFieldNumber = 2;
  inline const ::std::string& uuid_and_denom() const;
  inline void set_uuid_and_denom(const ::std::string& value);
  inline void set_uuid_and_denom(const char* value);
  inline void set_uuid_and_denom(const char* value, size_t size);
  inline ::std::string* mutable_uuid_and_denom();
  inline ::std::string* release_uuid_and_denom();
  inline void set_allocated_uuid_and_denom(::std::string* uuid_and_denom);

  // @@protoc_insertion_point(class_scope:currency.Currency)
 private:
  inline void set_has_uuid_and_denom();
  inline void clear_has_uuid_and_denom();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* uuid_and_denom_;
  friend void  protobuf_AddDesc_currency_2eproto();
  friend void protobuf_AssignDesc_currency_2eproto();
  friend void protobuf_ShutdownFile_currency_2eproto();

  void InitAsDefaultInstance();
  static Currency* default_instance_;
};
// ===================================================================


// ===================================================================

// Currency

// required string uuid_and_denom = 2;
inline bool Currency::has_uuid_and_denom() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Currency::set_has_uuid_and_denom() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Currency::clear_has_uuid_and_denom() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Currency::clear_uuid_and_denom() {
  if (uuid_and_denom_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    uuid_and_denom_->clear();
  }
  clear_has_uuid_and_denom();
}
inline const ::std::string& Currency::uuid_and_denom() const {
  // @@protoc_insertion_point(field_get:currency.Currency.uuid_and_denom)
  return *uuid_and_denom_;
}
inline void Currency::set_uuid_and_denom(const ::std::string& value) {
  set_has_uuid_and_denom();
  if (uuid_and_denom_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    uuid_and_denom_ = new ::std::string;
  }
  uuid_and_denom_->assign(value);
  // @@protoc_insertion_point(field_set:currency.Currency.uuid_and_denom)
}
inline void Currency::set_uuid_and_denom(const char* value) {
  set_has_uuid_and_denom();
  if (uuid_and_denom_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    uuid_and_denom_ = new ::std::string;
  }
  uuid_and_denom_->assign(value);
  // @@protoc_insertion_point(field_set_char:currency.Currency.uuid_and_denom)
}
inline void Currency::set_uuid_and_denom(const char* value, size_t size) {
  set_has_uuid_and_denom();
  if (uuid_and_denom_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    uuid_and_denom_ = new ::std::string;
  }
  uuid_and_denom_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:currency.Currency.uuid_and_denom)
}
inline ::std::string* Currency::mutable_uuid_and_denom() {
  set_has_uuid_and_denom();
  if (uuid_and_denom_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    uuid_and_denom_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:currency.Currency.uuid_and_denom)
  return uuid_and_denom_;
}
inline ::std::string* Currency::release_uuid_and_denom() {
  clear_has_uuid_and_denom();
  if (uuid_and_denom_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = uuid_and_denom_;
    uuid_and_denom_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Currency::set_allocated_uuid_and_denom(::std::string* uuid_and_denom) {
  if (uuid_and_denom_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete uuid_and_denom_;
  }
  if (uuid_and_denom) {
    set_has_uuid_and_denom();
    uuid_and_denom_ = uuid_and_denom;
  } else {
    clear_has_uuid_and_denom();
    uuid_and_denom_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:currency.Currency.uuid_and_denom)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace currency

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_currency_2eproto__INCLUDED
