// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: currency.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "currency.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace currency {

namespace {

const ::google::protobuf::Descriptor* Currency_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Currency_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_currency_2eproto() {
  protobuf_AddDesc_currency_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "currency.proto");
  GOOGLE_CHECK(file != NULL);
  Currency_descriptor_ = file->message_type(0);
  static const int Currency_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Currency, uuid_and_denom_),
  };
  Currency_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Currency_descriptor_,
      Currency::default_instance_,
      Currency_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Currency, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Currency, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Currency));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_currency_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Currency_descriptor_, &Currency::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_currency_2eproto() {
  delete Currency::default_instance_;
  delete Currency_reflection_;
}

void protobuf_AddDesc_currency_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\016currency.proto\022\010currency\"\"\n\010Currency\022\026"
    "\n\016uuid_and_denom\030\002 \002(\t", 62);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "currency.proto", &protobuf_RegisterTypes);
  Currency::default_instance_ = new Currency();
  Currency::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_currency_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_currency_2eproto {
  StaticDescriptorInitializer_currency_2eproto() {
    protobuf_AddDesc_currency_2eproto();
  }
} static_descriptor_initializer_currency_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int Currency::kUuidAndDenomFieldNumber;
#endif  // !_MSC_VER

Currency::Currency()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:currency.Currency)
}

void Currency::InitAsDefaultInstance() {
}

Currency::Currency(const Currency& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:currency.Currency)
}

void Currency::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  uuid_and_denom_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Currency::~Currency() {
  // @@protoc_insertion_point(destructor:currency.Currency)
  SharedDtor();
}

void Currency::SharedDtor() {
  if (uuid_and_denom_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete uuid_and_denom_;
  }
  if (this != default_instance_) {
  }
}

void Currency::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Currency::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Currency_descriptor_;
}

const Currency& Currency::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_currency_2eproto();
  return *default_instance_;
}

Currency* Currency::default_instance_ = NULL;

Currency* Currency::New() const {
  return new Currency;
}

void Currency::Clear() {
  if (has_uuid_and_denom()) {
    if (uuid_and_denom_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
      uuid_and_denom_->clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Currency::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:currency.Currency)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string uuid_and_denom = 2;
      case 2: {
        if (tag == 18) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_uuid_and_denom()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->uuid_and_denom().data(), this->uuid_and_denom().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "uuid_and_denom");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:currency.Currency)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:currency.Currency)
  return false;
#undef DO_
}

void Currency::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:currency.Currency)
  // required string uuid_and_denom = 2;
  if (has_uuid_and_denom()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->uuid_and_denom().data(), this->uuid_and_denom().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "uuid_and_denom");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->uuid_and_denom(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:currency.Currency)
}

::google::protobuf::uint8* Currency::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:currency.Currency)
  // required string uuid_and_denom = 2;
  if (has_uuid_and_denom()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->uuid_and_denom().data(), this->uuid_and_denom().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "uuid_and_denom");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->uuid_and_denom(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:currency.Currency)
  return target;
}

int Currency::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string uuid_and_denom = 2;
    if (has_uuid_and_denom()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->uuid_and_denom());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Currency::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Currency* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Currency*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Currency::MergeFrom(const Currency& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_uuid_and_denom()) {
      set_uuid_and_denom(from.uuid_and_denom());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Currency::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Currency::CopyFrom(const Currency& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Currency::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void Currency::Swap(Currency* other) {
  if (other != this) {
    std::swap(uuid_and_denom_, other->uuid_and_denom_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Currency::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Currency_descriptor_;
  metadata.reflection = Currency_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace currency

// @@protoc_insertion_point(global_scope)
