all:
	g++ -g -w -L/media/shrinivaasanka/OS/boost_1_57_0/boost_1_57_0/bin.v2/libs/ -I/media/shrinivaasanka/OS/boost_1_57_0/boost_1_57_0/ -I/media/shrinivaasanka/OS/boost_1_57_0/boost_1_57_0/boost/graph -I/usr/local/include -L/usr/local/lib -std=c++11 *.cpp -o EventNet_boostgraph 
clean:
	rm EventNet_BoostGL

